# Generated by Django 5.2.6 on 2025-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='color_choice',
            field=models.CharField(choices=[('oq', 'Oq'), ('qora', 'Qora'), ("ko'k", 'Ko‘k'), ('qizil', 'Qizil'), ('yashil', 'Yashil'), ('boshqa', 'Boshqa')], default='oq', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_choice',
            field=models.CharField(choices=[('paxta', 'Paxta'), ('jun', 'Jun'), ('ipak', 'Ipak'), ('sintetik', 'Sintetik'), ('boshqa', 'Boshqa')], default='paxta', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size_choice',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('boshqa', 'Boshqa')], default='m', max_length=20),
        ),
    ]
